//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgePrepNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizResult
    {
        public int ResultId { get; set; }
        public int StudentId { get; set; }
        public int QuizId { get; set; }
        public int Score { get; set; }
        public int TotalQuestions { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
    
        public virtual Quizze Quizze { get; set; }
        public virtual User User { get; set; }
    }
}
