//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgePrepNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int ScoreId { get; set; }
        public int StudentId { get; set; }
        public int QuizId { get; set; }
        public int Score1 { get; set; }
        public int TotalMarks { get; set; }
        public Nullable<System.DateTime> TakenAt { get; set; }
    }
}
